"""empty message

Revision ID: 362c125df40c
Revises: b2c7e2db7704
Create Date: 2023-03-06 17:17:33.452053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362c125df40c'
down_revision = 'b2c7e2db7704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=255), nullable=True))

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=255), nullable=True))

    with op.batch_alter_table('patrimony', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=255), nullable=True))

    with op.batch_alter_table('restoration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restoration', schema=None) as batch_op:
        batch_op.drop_column('contact')

    with op.batch_alter_table('patrimony', schema=None) as batch_op:
        batch_op.drop_column('contact')

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_column('contact')

    with op.batch_alter_table('accommodation', schema=None) as batch_op:
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
