"""empty message

Revision ID: 52dc7c7f29d3
Revises: 7fb6464e2679
Create Date: 2023-03-02 22:33:14.344726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52dc7c7f29d3'
down_revision = '7fb6464e2679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patrimony', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_region_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_constraint('region_user_region_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_region', ['user_region_id'], ['id'])
        batch_op.drop_column('user_region')

    with op.batch_alter_table('restoration', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('user_region', schema=None) as batch_op:
        batch_op.drop_constraint('user_region_address_key', type_='unique')
        batch_op.drop_constraint('user_region_city_key', type_='unique')
        batch_op.drop_constraint('user_region_country_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_region', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_region_country_key', ['country'])
        batch_op.create_unique_constraint('user_region_city_key', ['city'])
        batch_op.create_unique_constraint('user_region_address_key', ['address'])

    with op.batch_alter_table('restoration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_region', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('region_user_region_fkey', 'user_region', ['user_region'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_region_id')

    with op.batch_alter_table('patrimony', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
