"""empty message

Revision ID: 5d2a885bdebf
Revises: 7fb6464e2679
Create Date: 2023-03-09 19:42:03.010836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2a885bdebf'
down_revision = '7fb6464e2679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_region', schema=None) as batch_op:
        batch_op.drop_constraint('user_region_address_key', type_='unique')
        batch_op.drop_constraint('user_region_city_key', type_='unique')
        batch_op.drop_constraint('user_region_country_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_region', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_region_country_key', ['country'])
        batch_op.create_unique_constraint('user_region_city_key', ['city'])
        batch_op.create_unique_constraint('user_region_address_key', ['address'])

    # ### end Alembic commands ###
