"""empty message

Revision ID: 65e23f50eb0e
Revises: b60e80ae1408
Create Date: 2023-03-18 17:54:00.385731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e23f50eb0e'
down_revision = 'b60e80ae1408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('restoration', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restoration', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('region', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('accommodation', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
