"""empty message

Revision ID: 6fa7b8512c84
Revises: f1d0626c16ad
Create Date: 2023-03-06 17:05:32.023154

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6fa7b8512c84'
down_revision = 'f1d0626c16ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accommodation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_open', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('coordinates', sa.String(length=255), nullable=True))
        batch_op.alter_column('resume',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('type_bussiness',
               existing_type=postgresql.ENUM('hotel', 'hostal', 'albergue', 'casa_rural', name='accommodationchoices'),
               nullable=True,
               existing_server_default=sa.text("'hotel'::accommodationchoices"))
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_open', sa.String(length=255), nullable=True))
        batch_op.alter_column('resume',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('type_bussiness',
               existing_type=postgresql.ENUM('activo', 'gastronomico', 'historico', 'cultural', name='experiencechoices'),
               nullable=True,
               existing_server_default=sa.text("'activo'::experiencechoices"))
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('patrimony', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_open', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('coordinates', sa.String(length=255), nullable=True))

    with op.batch_alter_table('restoration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_open', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cart', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('coordinates', sa.String(length=255), nullable=True))
        batch_op.alter_column('resume',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('type_bussiness',
               existing_type=postgresql.ENUM('bar', 'chiringuito', 'restaurante', 'pub', name='restorationchoices'),
               nullable=True,
               existing_server_default=sa.text("'bar'::restorationchoices"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restoration', schema=None) as batch_op:
        batch_op.alter_column('type_bussiness',
               existing_type=postgresql.ENUM('bar', 'chiringuito', 'restaurante', 'pub', name='restorationchoices'),
               nullable=False,
               existing_server_default=sa.text("'bar'::restorationchoices"))
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('resume',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('coordinates')
        batch_op.drop_column('location')
        batch_op.drop_column('cart')
        batch_op.drop_column('time_open')

    with op.batch_alter_table('patrimony', schema=None) as batch_op:
        batch_op.drop_column('coordinates')
        batch_op.drop_column('location')
        batch_op.drop_column('time_open')

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('type_bussiness',
               existing_type=postgresql.ENUM('activo', 'gastronomico', 'historico', 'cultural', name='experiencechoices'),
               nullable=False,
               existing_server_default=sa.text("'activo'::experiencechoices"))
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('resume',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('time_open')

    with op.batch_alter_table('accommodation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('type_bussiness',
               existing_type=postgresql.ENUM('hotel', 'hostal', 'albergue', 'casa_rural', name='accommodationchoices'),
               nullable=False,
               existing_server_default=sa.text("'hotel'::accommodationchoices"))
        batch_op.alter_column('logo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('photo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('resume',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('coordinates')
        batch_op.drop_column('location')
        batch_op.drop_column('time_open')

    # ### end Alembic commands ###
