"""empty message

Revision ID: 789de158a81f
Revises: 816691c3f01d
Create Date: 2023-03-08 20:07:10.585633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789de158a81f'
down_revision = '816691c3f01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patrimony', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitud', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('latitud', sa.Float(), nullable=True))
        batch_op.drop_column('coordinates')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patrimony', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('latitud')
        batch_op.drop_column('longitud')

    # ### end Alembic commands ###
