"""empty message

Revision ID: 80a975bc588a
Revises: 853cd02428f6
Create Date: 2023-03-02 18:54:24.891825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80a975bc588a'
down_revision = '853cd02428f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_bussiness', sa.Enum('activo', 'gastronomico', 'historico', 'cultural', name='experiencechoices'), server_default='turismo activo', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_column('type_bussiness')

    # ### end Alembic commands ###
