"""empty message

Revision ID: 853cd02428f6
Revises: 4a2b9e7c72af
Create Date: 2023-02-26 13:28:29.201096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853cd02428f6'
down_revision = '4a2b9e7c72af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restoration', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restoration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
