"""empty message

Revision ID: a4a475616f16
Revises: 
Create Date: 2023-03-18 17:25:17.072567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a475616f16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('contact_person_name', sa.String(length=100), nullable=False),
    sa.Column('nif', sa.String(length=100), nullable=False),
    sa.Column('contact_person_telf', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_person_name'),
    sa.UniqueConstraint('contact_person_telf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('nif')
    )
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resume', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=False),
    sa.Column('coordinates', sa.String(length=255), nullable=True),
    sa.Column('user_region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_region_id'], ['user_region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('user_region_id')
    )
    op.create_table('accommodation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('time_open', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('coordinates', sa.String(length=255), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('type_bussiness', sa.Enum('hotel', 'hostal', 'albergue', 'casa_rural', name='accommodationchoices'), server_default='hotel', nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('time_open', sa.String(length=255), nullable=True),
    sa.Column('meeting_point', sa.String(length=255), nullable=True),
    sa.Column('coordinates', sa.String(length=255), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('type_bussiness', sa.Enum('activo', 'gastronomico', 'historico', 'cultural', name='experiencechoices'), server_default='activo', nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('patrimony',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resume', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=False),
    sa.Column('time_open', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('coordinates', sa.String(length=255), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('type_bussiness', sa.Enum('natural', 'cultural', 'historico', 'fiestas', name='patrimonychoices'), server_default='cultural', nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('restoration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('time_open', sa.String(length=255), nullable=True),
    sa.Column('cart', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('coordinates', sa.String(length=255), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('type_bussiness', sa.Enum('bar', 'chiringuito', 'restaurante', 'pub', name='restorationchoices'), server_default='bar', nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_region_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('restoration_id', sa.Integer(), nullable=True),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.Column('patrimony_id', sa.Integer(), nullable=True),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ),
    sa.ForeignKeyConstraint(['experience_id'], ['experience.id'], ),
    sa.ForeignKeyConstraint(['patrimony_id'], ['patrimony.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['restoration_id'], ['restoration.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_region_id'], ['user_region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('restoration_id', sa.Integer(), nullable=True),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.Column('patrimony_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodation.id'], ),
    sa.ForeignKeyConstraint(['patrimony_id'], ['patrimony.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], ),
    sa.ForeignKeyConstraint(['restoration_id'], ['restoration.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('comments')
    op.drop_table('restoration')
    op.drop_table('patrimony')
    op.drop_table('experience')
    op.drop_table('accommodation')
    op.drop_table('region')
    op.drop_table('user_region')
    op.drop_table('user')
    # ### end Alembic commands ###
