"""empty message

Revision ID: b2c7e2db7704
Revises: 6fa7b8512c84
Create Date: 2023-03-06 17:12:12.312280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c7e2db7704'
down_revision = '6fa7b8512c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_point', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('coordinates', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_column('coordinates')
        batch_op.drop_column('meeting_point')

    # ### end Alembic commands ###
