"""empty message

Revision ID: b60e80ae1408
Revises: fa0c924d560b
Create Date: 2023-03-18 17:51:04.758025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60e80ae1408'
down_revision = 'fa0c924d560b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patrimony', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patrimony', schema=None) as batch_op:
        batch_op.alter_column('coordinates',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
