"""empty message

Revision ID: f47e9e407991
Revises: 362c125df40c
Create Date: 2023-03-07 16:14:47.450271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f47e9e407991'
down_revision = '362c125df40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patrimony', schema=None) as batch_op:
        batch_op.alter_column('type_bussiness',
               existing_type=postgresql.ENUM('natural', 'cultural', 'historico', 'fiestas', name='patrimonychoices'),
               nullable=True,
               existing_server_default=sa.text("'cultural'::patrimonychoices"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patrimony', schema=None) as batch_op:
        batch_op.alter_column('type_bussiness',
               existing_type=postgresql.ENUM('natural', 'cultural', 'historico', 'fiestas', name='patrimonychoices'),
               nullable=False,
               existing_server_default=sa.text("'cultural'::patrimonychoices"))

    # ### end Alembic commands ###
